services:
  php:
    build: .
    container_name: todo_list_php
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
    env_file: .env
    networks:
      - todo-list-mariadb_default
    restart: unless-stopped

networks:
  todo-list-mariadb_default:
    external: true
